		<div id="wrapper">
			<div id="header" style="text-align: center; color: white;">
				<p style="font-weight: bold; font-size:400%">miniFacebook</p><br>
			</div>
			<div id="navigation">
				<nav id='menu'>
					<input type='checkbox' id='responsive-menu' onclick='updatemenu()'><label></label>
					<ul>
						<li><a href='fb_home_db.php'>홈</a></li>
						<li><a href='fb_search_v2_db.php'>회원검색</a></li>
						<li><a href='fb_view_db.php'>모든회원보기</a></li>
						<li><a href='fb_delete_db.php'>회원탈퇴</a></li>
						<li><a href='fb_update_db.php'>회원정보수정</a></li>
						<li><a href='fb_logout_db.php'>로그아웃</a></li>
					</ul>
				</nav>
			</div>