		<div id="wrapper">
			<div id="header" style="text-align: center; color: white;">
				<p style="font-weight: bold; font-size:400%">miniFacebook</p><br>
			</div>
			<div id="navigation">
				<nav id='menu'>
					<input type='checkbox' id='responsive-menu' onclick='updatemenu()'><label></label>
					<ul>
						<li><a href='fb_home_db.php'>홈</a></li>
						<li><a href='fb_register_db.php'>회원가입</a></li>
						<li><a href='fb_login_db.php'>로그인</a></li>
					</ul>
				</nav>
			</div>